# Generated by Django 2.1.7 on 2019-02-28 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_platform', '0002_auto_20190227_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_over',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='content',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='post_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='post_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='rent_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='detail',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='district',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_co_rent',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='latitude',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='location',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='longtitude',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='rank',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='size',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
