# Generated by Django 2.1.7 on 2019-02-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_platform', '0002_auto_20190226_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='house_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
