# Generated by Django 2.1.7 on 2019-03-01 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_platform', '0004_auto_20190301_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='rent_time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
