# Generated by Django 2.1.7 on 2019-03-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_platform', '0007_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='room_id',
            field=models.IntegerField(null=True),
        ),
    ]
