# Generated by Django 2.1.7 on 2019-03-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_platform', '0009_uploadimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimg',
            name='room_id',
            field=models.IntegerField(null=True),
        ),
    ]
