# Generated by Django 2.1.7 on 2019-03-01 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_platform', '0003_auto_20190228_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='room_id',
            field=models.IntegerField(),
        ),
    ]
